version: "3.8"
services:
  mysql:
    image: mysql:8.0.16
    container_name: app-mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}

  phpmyadmin:
    container_name: app-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: 'mysql'
      PMA_USER: ${PHPMYADMIN_DB_USERNAME}
      PMA_PASSWORD: ${PHPMYADMIN_DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: ${DB_UPLOAD_MAX_FILESIZE:-50M}
    volumes:
      - ./docker-config/db/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - default

  redis:
    build:
      context: ./docker-config/redis/
      dockerfile: Dockerfile
    container_name: app-redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - dbdata:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  dbdata:

networks:
  default:
    name: ${NETWORK_NAME:-news_network}
    driver: bridge
